# .github/workflows/deploy.yml
name: Deploy HTML to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 👈 Add this to allow manual deploys

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3
  app-name: helloworldtem
  slot-name: Production
  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  package: .
